name = "mbot"
type = "webpack"

compatibility_date = "2023-03-03"

workers_dev = true
main = "./index.js"

[[queues.producers]]
queue = "mbot-queue"
binding = "QUEUE"

# Worker also receives messages from the Queue, named "my-queue".
[[queues.consumers]]
queue = "mbot-queue"
max_batch_size = 1   # Max messages per batch
max_batch_timeout = 30 # Max seconds to wait before batch is full
max_retries = 2       # Max retries per batch